//! Authentication primitives for the private Telegram gateway protocol.

use rand::RngCore;
use serde::de::Error as _;
use subtle::ConstantTimeEq;

/// Current private gateway protocol version.
pub(crate) const PROTOCOL_VERSION: u32 = 0;
/// Only extension instance allowed to authenticate to this gateway.
pub(crate) const EXTENSION_INSTANCE: &str = "std-telegram";
const TRANSCRIPT_MAGIC: &[u8] = b"tau-telegram-gateway-auth";
const KEY_ID_DOMAIN: &[u8] = b"tau-telegram-gateway-key-id-v1";

/// A decoded gateway client authentication key.
#[derive(Clone)]
pub(crate) struct GatewayAuthKey {
    /// Secret bytes used only for keyed hashes and never rendered in
    /// diagnostics.
    bytes: [u8; 32],
}

impl std::fmt::Debug for GatewayAuthKey {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str("GatewayAuthKey(<redacted>)")
    }
}

macro_rules! canonical_hex_type {
    ($name:ident, $doc:literal) => {
        #[doc = $doc]
        #[derive(Clone, Debug, Eq, Hash, PartialEq, serde::Serialize)]
        #[serde(transparent)]
        pub(crate) struct $name(#[doc = "Canonical lowercase hexadecimal wire encoding."] String);

        impl $name {
            /// Parse the exact 32-byte lowercase hexadecimal wire encoding.
            pub(crate) fn parse(value: impl Into<String>) -> Result<Self, String> {
                let value = value.into();
                decode_fixed::<32>(&value)
                    .map(|_| Self(value))
                    .ok_or_else(|| "invalid Telegram gateway authentication field".to_owned())
            }

            /// Generate a cryptographically random value.
            pub(crate) fn random() -> Self {
                let mut bytes = [0_u8; 32];
                rand::rngs::OsRng.fill_bytes(&mut bytes);
                Self(encode_hex(&bytes))
            }

            /// Borrow the canonical wire encoding.
            pub(crate) fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                let value = String::deserialize(deserializer)?;
                Self::parse(value).map_err(serde::de::Error::custom)
            }
        }
    };
}

canonical_hex_type!(GatewayGeneration, "Random identity of one gateway process.");
canonical_hex_type!(
    ClientGeneration,
    "Process identity reused across client reconnects."
);
canonical_hex_type!(ClientNonce, "Fresh nonce generated by a gateway client.");
canonical_hex_type!(ServerNonce, "Fresh nonce generated by the gateway.");

/// Non-authoritative selector for one configured authentication key.
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize)]
#[serde(transparent)]
pub(crate) struct GatewayKeyId(
    /// Canonical lowercase hexadecimal wire encoding.
    String,
);

impl GatewayKeyId {
    /// Parse the exact 16-byte lowercase hexadecimal wire encoding.
    pub(crate) fn parse(value: impl Into<String>) -> Result<Self, String> {
        let value = value.into();
        decode_fixed::<16>(&value)
            .map(|_| Self(value))
            .ok_or_else(|| "invalid Telegram gateway authentication field".to_owned())
    }

    /// Borrow the canonical wire encoding.
    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

/// A validated fixed-size authentication proof.
#[derive(Clone)]
pub(crate) struct AuthProof(
    /// Validated proof bytes used only for constant-time comparison or
    /// encoding.
    [u8; 32],
);

impl AuthProof {
    /// Parse the exact lowercase hexadecimal proof encoding.
    pub(crate) fn parse(value: &str) -> Result<Self, String> {
        decode_fixed::<32>(value)
            .map(Self)
            .ok_or_else(|| "invalid Telegram gateway authentication proof".to_owned())
    }

    /// Render the canonical wire encoding.
    pub(crate) fn encode(&self) -> String {
        encode_hex(&self.0)
    }
}

impl<'de> serde::Deserialize<'de> for AuthProof {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::parse(&value).map_err(D::Error::custom)
    }
}

impl GatewayAuthKey {
    /// Parse the exact lowercase hexadecimal key format.
    pub(crate) fn parse(value: &str) -> Result<Self, String> {
        decode_fixed::<32>(value)
            .map(|bytes| Self { bytes })
            .ok_or_else(|| "invalid Telegram gateway client secret".to_owned())
    }

    /// Return the non-authoritative key selector.
    pub(crate) fn key_id(&self) -> GatewayKeyId {
        let digest = blake3::keyed_hash(&self.bytes, KEY_ID_DOMAIN);
        GatewayKeyId(encode_hex(&digest.as_bytes()[..16]))
    }

    /// Compute the gateway's proof for one handshake transcript.
    pub(crate) fn server_proof(&self, fields: &AuthFields<'_>) -> AuthProof {
        self.proof(fields, ProofRole::Server)
    }

    /// Compute the client's proof for one handshake transcript.
    pub(crate) fn client_proof(&self, fields: &AuthFields<'_>) -> AuthProof {
        self.proof(fields, ProofRole::Client)
    }

    /// Verify a fixed-size proof in constant time.
    pub(crate) fn verify_proof(&self, expected: &AuthProof, actual: &AuthProof) -> bool {
        bool::from(expected.0.ct_eq(&actual.0))
    }

    fn proof(&self, fields: &AuthFields<'_>, role: ProofRole) -> AuthProof {
        let mut input = Vec::with_capacity(256);
        for value in [
            TRANSCRIPT_MAGIC,
            role.as_bytes(),
            &PROTOCOL_VERSION.to_be_bytes(),
            fields.key_id.as_str().as_bytes(),
            fields.gateway_generation.as_str().as_bytes(),
            EXTENSION_INSTANCE.as_bytes(),
            fields.client_generation.as_str().as_bytes(),
            fields.client_nonce.as_str().as_bytes(),
            fields.server_nonce.as_str().as_bytes(),
        ] {
            input.extend_from_slice(&(value.len() as u32).to_be_bytes());
            input.extend_from_slice(value);
        }
        AuthProof(*blake3::keyed_hash(&self.bytes, &input).as_bytes())
    }
}

#[derive(Clone, Copy)]
enum ProofRole {
    Server,
    Client,
}
impl ProofRole {
    fn as_bytes(self) -> &'static [u8] {
        match self {
            Self::Server => b"server",
            Self::Client => b"client",
        }
    }
}

/// Immutable validated fields covered by both handshake proofs.
pub(crate) struct AuthFields<'a> {
    /// Validated selector for the configured shared key.
    pub(crate) key_id: &'a GatewayKeyId,
    /// Validated random identity of the gateway process.
    pub(crate) gateway_generation: &'a GatewayGeneration,
    /// Validated process identity retained across client reconnects.
    pub(crate) client_generation: &'a ClientGeneration,
    /// Validated nonce freshly generated by the client.
    pub(crate) client_nonce: &'a ClientNonce,
    /// Validated nonce freshly generated by the gateway.
    pub(crate) server_nonce: &'a ServerNonce,
}

fn decode_fixed<const N: usize>(value: &str) -> Option<[u8; N]> {
    if value.len() != N * 2
        || value
            .bytes()
            .any(|byte| !byte.is_ascii_digit() && !(b'a'..=b'f').contains(&byte))
    {
        return None;
    }
    let mut bytes = [0_u8; N];
    for (index, byte) in bytes.iter_mut().enumerate() {
        *byte = (hex_nibble(value.as_bytes()[index * 2])? << 4)
            | hex_nibble(value.as_bytes()[index * 2 + 1])?;
    }
    Some(bytes)
}
fn hex_nibble(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        _ => None,
    }
}
fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(HEX[usize::from(byte >> 4)] as char);
        encoded.push(HEX[usize::from(byte & 0x0f)] as char);
    }
    encoded
}

#[cfg(test)]
mod tests;
