[package]
name = "tau-supervisor"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rustix = { version = "0.38", default-features = false, features = [
  "process",
  "std",
] }
tau-proto.workspace = true

[dev-dependencies]
tempfile.workspace = true
