[package]
name = "tau-ext-xmpp"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
blake3.workspace = true
futures-util.workspace = true
handlebars.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tau-client.workspace = true
tau-proto.workspace = true
tokio.workspace = true
tokio-xmpp.workspace = true
tracing.workspace = true
xmpp-parsers.workspace = true

[dev-dependencies]
tau-core.workspace = true
tracing-subscriber.workspace = true
