[package]
name = "dpc-tau-skills"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "tau_skills"

[lints]
workspace = true

[dependencies]
serde_yaml_ng.workspace = true
tau-proto.workspace = true

[dev-dependencies]
tempfile.workspace = true
