[package]
name = "dpc-tau-ext-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "tau_ext_utils"

[lints]
workspace = true

[dependencies]
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
tau-client.workspace = true
tau-proto.workspace = true
tracing.workspace = true
[[bin]]
name = "tau-ext-utils"
path = "src/main.rs"
