[package]
name = "tau"
default-run = "tau"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tau-cli.workspace = true
tau-ext-pim.workspace = true
tau-ext-provider-builtin.workspace = true
tau-ext-rhai.workspace = true
tau-ext-rostra.workspace = true
tau-ext-shell.workspace = true
tau-ext-slack.workspace = true
tau-ext-std-notifications.workspace = true
tau-ext-swarm.workspace = true
tau-ext-telegram.workspace = true
tau-ext-test-dummy.workspace = true
tau-ext-utils.workspace = true
tau-ext-websearch.workspace = true
tau-ext-xmpp.workspace = true
tau-ext-zulip.workspace = true

[dev-dependencies]
serde_json.workspace = true
tau-harness.workspace = true
tau-proto.workspace = true
tau-socket.workspace = true
tempfile.workspace = true
