[package]
name = "tau-e2e-tests"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
blake3.workspace = true
fs2.workspace = true
image.workspace = true
nix = { version = "0.29", default-features = false, features = [
  "fs",
  "inotify",
  "poll",
  "process",
  "signal",
  "term",
  "time",
] }
rustix-v1 = { workspace = true, features = ["event", "process"] }
serde.workspace = true
serde_json.workspace = true
tau-client.workspace = true
tau-config.workspace = true
tau-core = { workspace = true, features = ["test-legacy-writer"] }
tau-ext-test-dummy.workspace = true
tau-harness = { workspace = true, features = ["output-length-test-barrier"] }
tau-harness-tools.workspace = true
tau-proto.workspace = true
tau-socket.workspace = true
tau-test-support.workspace = true
tau-util-fs-err.workspace = true
tau-vcr.workspace = true
tempfile.workspace = true
vt100.workspace = true
