[package]
name = "dpc-tau-util-fs-err"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "tau_util_fs_err"

[lints]
workspace = true

[dependencies]
fs-err.workspace = true

[dev-dependencies]
tempfile.workspace = true
