[package]
name = "dpc-tau-themes"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
json5 = { workspace = true }
serde = { workspace = true }

[lib]
name = "tau_themes"

[lints]
workspace = true
